# Generated by Django 6.0.6 on 2026-07-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('selary', models.IntegerField()),
                ('isHappy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
            ],
            options={
                'verbose_name': 'work',
                'verbose_name_plural': 'works',
            },
        ),
    ]
