# Generated by Django 6.0.6 on 2026-07-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='selary',
            new_name='selery',
        ),
    ]
